# SPDX-FileCopyrightText: 2024 sudo-tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure cadvisor base path exists
  ansible.builtin.file:
    path: "{{ cadvisor_base_path }}"
    state: directory
    mode: 0700
    owner: "{{ cadvisor_uid }}"
    group: "{{ cadvisor_gid }}"

- name: Ensure cadvisor support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ cadvisor_base_path }}/{{ item }}"
    owner: "{{ cadvisor_uid }}"
    group: "{{ cadvisor_gid }}"
    mode: 0640
  with_items:
    - labels
    - env

- name: Ensure cadvisor image is pulled
  community.docker.docker_image:
    name: "{{ cadvisor_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ cadvisor_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else cadvisor_docker_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure cadvisor container network is created
  community.general.docker_network:
    name: "{{ cadvisor_container_network }}"
    driver: bridge

- name: Ensure cadvisor systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/cadvisor.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ cadvisor_identifier }}.service"
    mode: 0644
