# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 sudo-tiz
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure cAdvisor path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ cadvisor_uid }}"
    group: "{{ cadvisor_gid }}"
  with_items:
    - "{{ cadvisor_base_path }}"

- name: Ensure cAdvisor support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ cadvisor_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ cadvisor_uid }}"
    group: "{{ cadvisor_gid }}"
  with_items:
    - env
    - labels

- name: Ensure cAdvisor container image is pulled
  community.docker.docker_image:
    name: "{{ cadvisor_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ cadvisor_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else cadvisor_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure cAdvisor container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ cadvisor_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure cAdvisor systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/cadvisor.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ cadvisor_identifier }}.service"
    mode: 0644
