# SPDX-FileCopyrightText: 2024 sudo-tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure cadvisor is installed
  tags:
    - setup-all
    - setup-cadvisor
    - install-all
    - install-cadvisor
  block:
    - name: Include cadvisor config validation tasks
      when: cadvisor_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Include cadvisor installation tasks
      when: cadvisor_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Ensure cadvisor is removed
  tags:
    - setup-all
    - setup-cadvisor
  block:
    - name: Include cadvisor removal tasks
      when: not cadvisor_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
