# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 sudo-tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform cAdvisor installation tasks
  tags:
    - setup-all
    - setup-cadvisor
    - install-all
    - install-cadvisor
  block:
    - name: Validate cAdvisor configuration
      when: cadvisor_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install cAdvisor
      when: cadvisor_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform cAdvisor uninstallation tasks
  tags:
    - setup-all
    - setup-cadvisor
  block:
    - name: Uninstall cAdvisor
      when: not cadvisor_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
