# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 sudo-tiz
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of cAdvisor systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ cadvisor_identifier }}.service"
  register: cadvisor_service_stat

- when: cadvisor_service_stat.stat.exists | bool
  block:
    - name: Ensure cAdvisor systemd service is stopped
      ansible.builtin.service:
        name: "{{ cadvisor_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure cAdvisor systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ cadvisor_identifier }}.service"
        state: absent

    - name: Ensure cAdvisor path does not exist
      ansible.builtin.file:
        path: "{{ cadvisor_base_path }}"
        state: absent
