# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 sudo-tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "cadvisor_docker_image", "new": "cadvisor_container_image" }
    - { "old": "cadvisor_docker_image_name_prefix", "new": "cadvisor_container_image_registry_prefix" }
    - { "old": "cadvisor_docker_image_force_pull", "new": "cadvisor_container_image_force_pull" }
    - { "old": "cadvisor_environment_variables_extension", "new": "cadvisor_environment_variables_additional_variables" }

- name: Fail if required cAdvisor settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - cadvisor_uid
    - cadvisor_gid
    - cadvisor_container_network

- name: Run if Traefik is enabled
  when: cadvisor_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for cAdvisor are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - cadvisor_container_labels_traefik_hostname
        - cadvisor_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `cadvisor_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if cadvisor_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          cadvisor_container_labels_traefik_path_prefix (`{{ cadvisor_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/cadvisor`).
      when: "cadvisor_container_labels_traefik_path_prefix != '/' and cadvisor_container_labels_traefik_path_prefix[-1] == '/'"
