# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 sudo-tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'cadvisor_docker_image', 'new': 'cadvisor_container_image'}
    - {'old': 'cadvisor_docker_image_name_prefix', 'new': 'cadvisor_container_image_registry_prefix'}
    - {'old': 'cadvisor_docker_image_force_pull', 'new': 'cadvisor_container_image_force_pull'}

- name: Fail if required cAdvisor settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - cadvisor_uid
    - cadvisor_gid
    - cadvisor_container_network

- when: cadvisor_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required cAdvisor Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - cadvisor_container_labels_traefik_hostname
        - cadvisor_container_labels_traefik_path_prefix
